// components/Home/CardBlog.tsx
import { motion } from 'framer-motion'
import Link from 'next/link'

type Prop = {
  img: string
  title: string
  category?: string
  description: string
  link?: string
}

const CardBlog = (props: Prop) => {


  return (
    <motion.div
      initial={{ y: 48, opacity: 0 }}
      whileHover={{ scale: 1.05 }}
      whileInView={{ y: 0, opacity: 1, transition: { duration: 0.6 } }}
      className="mt-[32px] max-w-[587px] p-2 cursor-pointer ">
      <Link href={props.link ? `${props.link}` : `./blog/${props.id}`} passHref>
        <div>
          <a target="_blank">
            <img src={props.img} className="border-2 border-[#ABAAAA]" />
            <h2 className="mt-2 text-[24px] text-[#01A7C2]">{props.title}</h2>
            <h3 className=" text-[20px] text-[#ABAAAA]">{props.category}</h3>
            <p className=""> {props.description}</p>
          </a>
        </div>
      </Link>
    </motion.div>
  )
}

export default CardBlog

// src/components/ui/CardBlog.svelte
<script>
  export let img;
  export let title
  export let linkPost
  export let category
  export let description
</script>

<div class="card-container">
  <!-- <a  href="{`/blog/${linkPost}`}"> -->
    <img src="{img}"/>
    <div class="text">
      <h2 class="title-font">{title}</h2>
      <h3>{category}</h3>
      <p>{description}</p>
          <a href="{`/blog/${linkPost}`}"
            target="_blank"
            class="button">
            Read
          </a>
  </div>

</div>

<style>

  .card-container{
    width:46%;
    margin-bottom:20px;
    /* width:100%; */
    /* display:flex;
       padding: 20px 0px;
       border-bottom: var(--border-brutal); */
  }
  .text{
    max-width: 100%;
  }

  h2{
    margin:0px;
    font-weight:normal;
    font-size:40px;
  }
  h3{
    font-size:20px;
    margin:0px;
    font-weight:normal;
  }
  img{
    width:100%;
    border: var(--border-brutal);
    margin: 0px;
  }
  @media (max-width: 860px){

    .card-container{
      width:100%;
      margin-bottom:20px;
    /* width:100%; */
    /* display:flex;
       padding: 20px 0px;
       border-bottom: var(--border-brutal); */
  }
  }
</style>
